import React, { useState } from "react";
import { ChevronDown, ChevronUp, Video } from "lucide-react";
import { Button } from "@/components/ui/button";
import { VideoAnnotationTutorial } from "@/components/VideoAnnotationTutorial";

interface FAQItem {
  question: string;
  answer: string;
}

const faqs: FAQItem[] = [
  {
    question: "How do I draw on my video files?",
    answer: "You can annotate video thumbnails! Click any video file in the Files tab to open the lightbox preview. Click the pencil icon (✏️) in the top toolbar to enter annotation mode. You'll have access to drawing tools including pen, shapes, arrows, text, and an eraser. Your annotations are automatically saved and can be exported as PNG images to share with your video editor. Press 'A' as a keyboard shortcut to toggle annotation mode."
  },
  {
    question: "How do I upload files?",
    answer: "Click the 'Upload Files' button in the Files tab, or drag and drop files directly into the file grid. You can upload images, videos, and documents. The system will automatically extract metadata from your files and optionally enrich them with AI-generated tags and descriptions."
  },
  {
    question: "What is AI enrichment?",
    answer: "AI enrichment automatically analyzes your files to generate descriptive tags, extract text (OCR), detect objects, and create searchable metadata. You can enable or disable enrichment during upload, or use the 'Re-enrich' button to retry enrichment on existing files."
  },
  {
    question: "How do collections work?",
    answer: "Collections help you organize related files together. Create a collection from the Collections tab, then drag files from the Files tab onto the collection in the sidebar. You can also use bulk operations to add multiple files to a collection at once. Files can belong to multiple collections."
  },
  {
    question: "Can I search across all my files?",
    answer: "Yes! Use the Search tab to find files by title, description, tags, or metadata. You can also use advanced filters to narrow results by file type, date range, enrichment status, or quality score. Save frequently-used searches for quick access."
  },
  {
    question: "How do I export my files?",
    answer: "Select one or more files in the Files tab, then click the 'Export as ZIP' button in the bulk operations toolbar. All selected files will be downloaded as a single ZIP archive. You can also export individual files by clicking the download button in the file preview lightbox."
  },
  {
    question: "What are tags and how do I use them?",
    answer: "Tags are keywords that help categorize and find your files. Tags can be added manually, extracted from file metadata, or generated by AI enrichment. Use the bulk operations toolbar to add tags to multiple files at once, or edit tags in the file detail view."
  },
  {
    question: "How do I delete files?",
    answer: "Select files in the Files tab and click the delete button in the bulk operations toolbar, or click the delete button in the file detail view. Deleted files can be restored using the 'Undo' button that appears immediately after deletion."
  },
  {
    question: "What is the Knowledge Graph?",
    answer: "The Knowledge Graph visualizes relationships between your files based on semantic similarity. Files with similar content, tags, or metadata are connected, helping you discover related content you might have forgotten about."
  },
  {
    question: "Can I record videos directly in the app?",
    answer: "Yes! Go to the Videos tab and click 'Start Recording' to record video with your webcam. The system provides live speech-to-text transcription and automatically suggests related files from your library based on what you're saying."
  },
  {
    question: "How do video annotations work?",
    answer: "When recording videos, the system detects keywords in your speech and suggests matching files from your library. You can accept these suggestions to create annotations at specific timestamps. Later, you can export the video with picture-in-picture overlays showing the annotated files."
  },
  {
    question: "What file types are supported?",
    answer: "MetaClips supports images (JPG, PNG, GIF, WebP), videos (MP4, WebM, MOV), and documents (PDF). Each file type has specific features - for example, images can be annotated with drawings, while videos support timestamp-based annotations."
  },
  {
    question: "How do I manage my account?",
    answer: "Go to Settings → Account to edit your profile, manage email preferences, or deactivate your account. You can update your name, location, company, job title, and other profile information."
  },
  {
    question: "Can I share my collections with others?",
    answer: "Collection sharing is planned for a future update. Currently, you can export collections as ZIP files and share them manually."
  },
  {
    question: "What happens to my data if I deactivate my account?",
    answer: "When you deactivate your account, your profile is marked as inactive but your data is retained. Contact support if you need to permanently delete your data."
  }
];

function FAQAccordionItem({ item, isOpen, onToggle }: { item: FAQItem; isOpen: boolean; onToggle: () => void }) {
  return (
    <div className="border-b border-border last:border-0">
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between gap-4 py-4 text-left hover:bg-accent/50 px-4 transition-colors"
      >
        <h3 className="text-base font-medium">{item.question}</h3>
        {isOpen ? (
          <ChevronUp className="h-5 w-5 text-muted-foreground flex-shrink-0" />
        ) : (
          <ChevronDown className="h-5 w-5 text-muted-foreground flex-shrink-0" />
        )}
      </button>
      {isOpen && (
        <div className="px-4 pb-4 text-sm text-muted-foreground">
          {item.answer}
        </div>
      )}
    </div>
  );
}

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);
  const [showTutorial, setShowTutorial] = useState(false);

  return (
    <div className="container max-w-4xl py-8">
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold">Frequently Asked Questions</h1>
            <p className="text-muted-foreground mt-2">Find answers to common questions about MetaClips</p>
          </div>
          <Button onClick={() => setShowTutorial(true)} className="flex items-center gap-2">
            <Video className="h-4 w-4" />
            Video Tutorial
          </Button>
        </div>
        <div>
          <h1 className="text-3xl font-bold">Frequently Asked Questions</h1>
          <p className="text-muted-foreground mt-2">
            Find answers to common questions about using MetaClips
          </p>
        </div>

        <div className="bg-card rounded-lg border">
          {faqs.map((faq, index) => (
            <FAQAccordionItem
              key={index}
              item={faq}
              isOpen={openIndex === index}
              onToggle={() => setOpenIndex(openIndex === index ? null : index)}
            />
          ))}
        </div>

        <div className="bg-muted/50 rounded-lg p-6">
          <h2 className="text-lg font-semibold mb-2">Still have questions?</h2>
          <p className="text-sm text-muted-foreground mb-4">
            If you can't find the answer you're looking for, please reach out to our support team.
          </p>
          <a
            href="/contact"
            className="inline-flex items-center justify-center rounded-md bg-primary text-primary-foreground px-4 py-2 text-sm font-medium hover:bg-primary/90 transition-colors"
          >
            Contact Support
          </a>
        </div>
      </div>

      <VideoAnnotationTutorial 
        open={showTutorial}
        onOpenChange={setShowTutorial}
      />
    </div>
  );
}
